### ISSUE TITLE
M1 Deliverable updates: User interface Requirements

### ISSUE THREAD

**Issue by xllRyan** [2101035/ICT2201-Team-Project-p1-7#51]

**Comment by Sy989** [comment]
UIR1: NHS Logo
UIR2: Color tones of purple (#592a9c) and White (#FDEDFD)
UIR3: Font size 14pt

2.2.3 Functional Requirements
FR1: The system shall allow staff to see their weekly job assignments, 
FR2: The system shall generate a job workload display on the landing page for the staff.
FR3: The system shall allow staff to add their unavailability up to 5 weeks ahead of time
FR4: The system shall allow staff to edit their availability up to 5 weeks ahead of time
FR5: The staff can reject job assigned by manager
FR6: The staff is able to indicate their job allocation for the week
FR7: The staff schedule is available by default 
FR8: The system shall display the dates that have been allocated for the month
FR9: Manager and staff will change their password after every 90 days
FR10: Manager can view staff workload(number of hours they have to work) on the manager landing page
FR11: Manager can view up to 3 staffs availability according to the top 3 lowest workload on the manager landing page
FR12: Manager views staff with over 40 hours of workload for the week on the manager landing page
FR13: Manager assigns staff for job allocation for 1 week at a time
FR14: Manager can view the staff’s assigned workload on the landing page
FR15: Manager can view staff job preference for the week
FR16: Manager can view the staff’s location at a particular date
FR17:The IT Administrator will add new staff into the system.
FR18: The IT Administrator will add new managers into the system

2.2.4 Non-Functional Requirements
NFR1: The system shall require the user to be connected to the hospital network to log in
NFR2: The system shall be displayed in the English Language.
NFR3: The system will be able to support browser versions on any web browser.
NFR4: The system will keep a backlog of data for up to one year.

2.2.5 Performance Requirements
NFR5: The system will need to be able to support the high load of traffic
NFR6: The system shall only be used on hospital premises when connected to the hospital network infrastructure
NFR7: The page should not take more than 5 seconds. So that staff can remain focused on their work

2.2.6 Safety and Security Requirements 
NFR8: Data transmitted from and received are always encrypted with AES-128.
NFR9: All approving roles must use a different factor of authentication from the user authentications (on top of 2FA) for approval processes.
NFR10: Website should be in HTTPS
NFR11: Website is not able to be exploitable by SQL injection
NFR12: PDPA ACT where organizations are not allowed to share clients' medical information with others

**Comment by Elsonnnn** [comment]
ok nice

**Comment by xllRyan** [comment]
good
